// <auto-generated />
namespace Examen_ASP.Net.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class unique_email : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(unique_email));
        
        string IMigrationMetadata.Id
        {
            get { return "202201080123146_unique_email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
