// <auto-generated />
namespace Examen_ASP.Net.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class messagemodif : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(messagemodif));
        
        string IMigrationMetadata.Id
        {
            get { return "202201112152345_message modif"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
