// <auto-generated />
namespace Examen_ASP.Net.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class loginrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loginrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202201081321469_login-required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
